version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "443:443"
      - "80:80"
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
    networks:
      - pythonapp

networks:
  pythonapp: